export enum lang {
    UA = 0,
    EN = 1,
};
export type language = lang.UA | lang.EN;

export default {
    // home
    "menu": ["Меню", "Main"],
    "open_character": ["Відкрити персонажа", "Open a character"],
    "open_campaign": ["Відкрити кампанію", "Open a campaign"],
    "create_campaign": ["Створити кампанію", "New character"],
    // character or master token
    "provide_your_token": ["Введіть ваш токен", "Providde your token"],
    "confirm": ["Підтвердити", "Confirm"],
    "back": ["Назад", "Back"],
    // master
    "campaign": ["Кампанія", "Campaign"],
    "update": ["Оновити", "Update"],
    "revoke_token": ["Скинути токен", "Revoke token"],
    "add_character": ["Додати персонажа", "New character"],
    "delete_character": ["Видалити персонажа", "Delete a character"],
    "provide_character_token": ["Введіть токен персонажа", "Provide the character's token"],
    "confirm_delete_character": ["Ви впевнені, що хочете видалити цього персонажа?", "Are you sure that you want to delete this character?"],
    "confirm_revoke_token": ["Ви впевнені, що хочете скинути цей токен?", "Are you sure that you want to revoke this token?"],
    "copy_token": ["Скопіювати токен", "Copy token"],
    "characters": ["Персонажі", "Characters"],
    // sheet
    // other params
    "copy_link": ["Скопіювати посилання", "Copy link"],
    "lock": ["Заблокувати", "Lock"],
    "edit": ["Редагувати", "Edit"],
    "player_name": ["Ім'я гравця", "Player name"],
    "name": ["Ім'я", "Name"],
    "description": ["Опис", "Description"],
    "rase": ["Раса", "Rase"],
    "attribute_points": ["Бали атрибутів", "Attribute points"],
    "skill_points": ["Бали вмінь", "Skill points"],
    "bonus_points": ["Бонусні бали", "Bonus points"],
    "additional_spendings": ["Додаткові витрати", "Additional spendings"],
    "size": ["Розмір", "Size"],
    "speed": ["Швидкість", "Speed"],
    "weight_multiplier": ["Множник ваги", "Weight multiplier"],
    "money": ["Гроші", "Money"],
    "wounds": ["Рани", "Wounds"],
    "fatigue": ["Втома", "Fatigue"],
    "bennies": ["Бені", "Bennies"],
    "other_parameters": ["Інші параметри", "Other parameters"],
    // tools
    "resources_tools": ["Ресурси та інструменти", "Tools and resourses"],
    "title": ["Назва", "Title"],
    "weight": ["Вага", "Weight"],
    "quantity": ["Кількість", "Quantity"],
    // derived
    "derived_statistics": ["Похідна статистика", "Derived statistics"],
    "parry": ["Захист", "Parry"],
    "toughness": ["Стійкість", "Toughness"],
    "load": ["Навантаження", "Load"],
    "upgrades": ["Прокачка", "Upgrades"],
    // armor
    "armor": ["Броня", "Armor"],
    "price": ["Ціна", "Price"],
    "min_strength": ["Мін. сила", "Min. strength"],
    "worn": ["Одягнено", "Worn"],
    "h_head": ["Г👩‍🦲", "H👩‍🦲"],
    "t_torso": ["Т🦺", "T🦺"],
    "a_arms": ["Р💪", "A💪"],
    "l_legs": ["Н🦵", "L🦵"],
    // shields
    "bonus": ["Бонус", "Bonus"],
    "cover": ["Укриття", "Cover"],
    "shields": ["Щити", "Shields"],
    // weapons
    "damage": ["Ушкодження", "Damage"],
    "armor_piercing": ["Проникнення", "Armor piercing"],
    "range": ["Дистанція", "Range"],
    "rate_of_fire": ["Частота", "Rate of fire"],
    "details": ["Додатково", "Details"],
    "melee": ["Ближня", "Melee"],
    "ranged": ["Дальня", "Ranged"],
    "weapons": ["Зброя", "Weapons"],
    // edges & hindrances
    "edges": ["Сильні сторони", "Edges"],
    "hindrances": ["Недоліки", "Hindrances"],
    // attributes
    "attributes": ["Атрибути", "Attributes"],
    "agility": ["Спритність", "Agility"],
    "smarts": ["Розум", "Smarts"],
    "spirit": ["Дух", "Spirit"],
    "strength": ["Сила", "Strength"],
    "vigor": ["Міцність", "Vigor"],
    // skills
    "skills": ["Вміння", "Skills"],
    "common_knowledge": ["Загальні Знання", "Common Knowledge"],
    "notice": ["Уважність", "Notice"],
    "persuasion": ["Переконання", "Persuasion"],
    "stealth": ["Непомітність", "Stealth"],
    "athletics": ["Атлетика", "Athletics"],
    "boating": ["Судноплавство", "Boating"],
    "driving": ["Водіння", "Driving"],
    "fighting": ["Боротьба", "Fighting"],
    "thievery": ["Злодійство", "Thievery"],
    "piloting": ["Пілотування", "Piloting"],
    "riding": ["Їзда Верхи", "Riding"],
    "shooting": ["Стрільба", "Shooting"],
    "gambling": ["Азартні Ігри", "Gambling"],
    "healing": ["Лікування", "Healing"],
    "research": ["Дослідження", "Research"],
    "repair": ["Ремонт", "Repair"],
    "survival": ["Виживання", "Survival"],
    "taunt": ["Насмішка", "Taunt"],
    "guts": ["Сміливість", "Guts"],
    "intimidation": ["Залякування", "Intimidation"],
    "psionics": ["Псионіка", "Psionics"],
    "focus": ["Концентрація", "Focus"],
    "faith": ["Віра", "Faith"],
    "electronics": ["Електроніка", "Electronics"],
    "battle": ["Тактика", "Battle"],
    "weird_science": ["Дивна Наука", "Weird Science"],
    "spellcasting": ["Заклинання", "Spellcasting"],
    "performance": ["Виступ", "Performance"],
    "hacking": ["Гакерство", "Hacking"],
    // other
    "untitled": ["Без Назви", "Untitled"],
    "character": ["Персонаж", "Character"],
};